travis:
  secure:
    BINSTAR_TOKEN: SZG1tfJB0YaaNux60+O2Wmgs3gAQ+j4SKhJH0XmW/Ex+GACJM4JPrFWzVxG7+oH/MbPTh2ORkHQQEJftfEouMSW7sCeeqg0xgAQN/IATf8PADPjPII/+gEolE9S/EIPOiDIQ34QDqFhozPIBJ0RmgoW+ad80jlxFM/m9blo8+o06U9Y4dTrhre9KA53SZZTcEf6rDNGctjpLv/1sEWet6bu6ChI3JZ8K+ErbUZgYyBP1TulWvG7P9MBjp3QO8fH2etOWqSJWBJ25Dp4nT6cHhU9sGXWRCaWBQWcQDCV+fO22hEHohZCJRq0utvjUgaXE70zkPC72znSynU20yNNoIZ+QVTUbmb4Y0IkSM6ZjDYjGmINxHQIHpNbF+OKPDRaYntSkBcj1vAEWVkmYWY1JhccKBxGnPZvt3yDcWjfZWQpdvwaTrxJt//MaF4pk63n7Cx7vGQVQ19fpyPPIhv307GKbpNfDoDo7CorCv34pY5FiuVBfIGv3LtIXUp+LPyQRlRGNhXGcYJ2jRAJqH5jiyhd+GWReS8MOaQFaqxLT0waLP3MFx3hKkR5zXNU5OONPDeQBNfK5rNRj8PZgVLFK/nRnVIHGKQkx54Di16B3IqOiKcCemqYba4lVWgsBqNY+LGG7CT+QjTmLjBJbetOL5Ul2+D7jD5iClmHKGdHsCDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
